FROM python:3.11

COPY ./test/perf/test-requirements.txt /test-requirements.txt

RUN pip install -r test-requirements.txt

RUN pip install bs4 docopt flask msgpack-python nanomsg pyzmq uvloop==0.21.0

COPY . /package

WORKDIR /package

RUN pip install -r /package/requirements.txt

CMD python test/perf/perftest.py
