FROM registry.tools.cosmic.sky/identity/sre/build_python_mite_packages
RUN set -ex \
    && apk add --no-cache curl-dev \
    && pip install -v https://github.com/tonysimpson/acurl/archive/master.zip
