{
 "title": "Mite Selenium",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Prometheus", "query": "prometheus" },
   { "name": "time_range", "label": "Time Range", "query": "5m" },
   { "name": "app", "query": "idris-frontend.*, .*" },
   { "name": "service", "query": "sign-in, sign-up" },
   {
    "name": "transaction",
    "query": {
     "query": "mite_transaction_total{application=~\"$app\"}"
    }
   },
   {
    "name": "http_metric",
    "label": "HTTP metric",
    "query": "mite_http_response_time_seconds, mite_http_response_time_minus_latency_seconds"
   }
  ]
 },
 "panels": [
  { "title": "Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Response Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(histogram_quantile(0.99999, sum by (le) (rate(${http_metric}_bucket{application=~\"$app\",transaction=~\"${transaction:regex}\"}[2s])))) < 60",
     "legendFormat": "99.999%"
    },
    {
     "expr": "(histogram_quantile(0.9999, sum by (le) (rate(${http_metric}_bucket{application=~\"$app\",transaction=~\"${transaction:regex}\"}[2s])))) < 60",
     "legendFormat": "99.99%"
    },
    {
     "expr": "(histogram_quantile(0.999, sum by (le) (rate(${http_metric}_bucket{application=~\"$app\",transaction=~\"${transaction:regex}\"}[2s])))) < 60",
     "legendFormat": "99.9%"
    },
    {
     "expr": "(histogram_quantile(0.99, sum by (le) (rate(${http_metric}_bucket{application=~\"$app\",transaction=~\"${transaction:regex}\"}[2s])))) < 60",
     "legendFormat": "99%"
    },
    {
     "expr": "(histogram_quantile(0.95, sum by (le) (rate(${http_metric}_bucket{application=~\"$app\",transaction=~\"${transaction:regex}\"}[2s])))) < 60",
     "legendFormat": "95%"
    },
    {
     "expr": "(histogram_quantile(0.9, sum by (le) (rate(${http_metric}_bucket{application=~\"$app\",transaction=~\"${transaction:regex}\"}[2s])))) < 60",
     "legendFormat": "90%"
    },
    {
     "expr": "(histogram_quantile(0.75, sum by (le) (rate(${http_metric}_bucket{application=~\"$app\",transaction=~\"${transaction:regex}\"}[2s])))) < 60",
     "legendFormat": "75%"
    },
    {
     "expr": "(histogram_quantile(0.5, sum by (le) (rate(${http_metric}_bucket{application=~\"$app\",transaction=~\"${transaction:regex}\"}[2s])))) < 60",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Slowest Response Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(histogram_quantile(0.99, sum by (transaction, le)(rate(${http_metric}_bucket{application=~\"$app\",transaction=~\"${transaction:regex}\"}[2s]))) > 1) < 60",
     "legendFormat": "{{transaction}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Journeys Failed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(mite_transaction_total{application=~\"$app\",had_error=\"True\", transaction!=\"__root__\",transaction=~\"${transaction:regex}\"}[30s]) / on (transaction, journey, test) sum(rate(mite_transaction_total{application=~\"$app\", transaction!=\"__root__\",transaction=~\"${transaction:regex}\"}[30s])) without (had_error) * 100",
     "legendFormat": "{{transaction}}"
    }
   ]
  },
  {
   "title": "Error Details",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, job)(rate(mite_journey_error_total{application=~\"$app\",transaction=~\"${transaction:regex}\"}[30s]))",
     "legendFormat": "{{transaction}} - {{message}} - {{location}}"
    }
   ]
  },
  {
   "title": "Percentage Transactions Failed",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(mite_transaction_total{application=~\"$app\",had_error=\"True\",transaction!=\"__root__\",transaction=~\"${transaction:regex}\"}[$time_range])) by (transaction, journey, test) / on (transaction, journey, test) (sum(rate(mite_transaction_total{application=~\"$app\",transaction!=\"__root__\"}[$time_range])) by (transaction, journey, test) > 0) * 100"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum without(instance, job, test, transaction,namespace,pod,deployment,application)(rate(mite_journey_error_total{application=~\"$app\",transaction=~\"${transaction:regex}\"}[30s])) > 0"
    }
   ]
  },
  { "title": "TPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "HTTP Responses Per Second",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "TPS" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mite_http_response_total{application=~\"$app\",transaction=~\"${transaction:regex}\"}[5s]))",
     "legendFormat": "Total requests"
    },
    {
     "expr": "sum by(method, response_code)(rate(mite_http_response_total{application=~\"$app\",transaction=~\"${transaction:regex}\"}[5s]))",
     "legendFormat": " {{method}}  {{response_code}}"
    }
   ]
  },
  {
   "title": "Journey Starts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (journey) (rate(mite_transaction_total{application=~\"$app\",transaction=~\"${transaction:regex}\"}[5s]))",
     "legendFormat": "{{journey}}"
    }
   ]
  },
  {
   "title": "Transactions/Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "TPS" }
   ],
   "targets": [
    {
     "expr": "sum by (transaction) (rate(mite_transaction_total{application=~\"$app\",transaction=~\"${transaction:regex}\"}[5s]))",
     "legendFormat": "{{transaction}}"
    }
   ]
  },
  { "title": "Runners", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Actual vs required jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, job, scenario_id, test, pod, test) (mite_required_count{application=~\"$app\"})",
     "legendFormat": "Required"
    },
    {
     "expr": "sum without(instance, job, scenario_id, test, pod, test) (mite_actual_count{application=~\"$app\"})",
     "legendFormat": "Actual"
    }
   ]
  },
  {
   "title": "Active Runners",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mite_runner_count{application=~\"$app\"})",
     "legendFormat": "Active Runners"
    }
   ]
  }
 ]
}