{
 "title": "Mite Docker",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "time_range", "label": "Time Range", "query": "5m" }
  ]
 },
 "panels": [
  {
   "title": "Response Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(histogram_quantile(0.99999, sum without(job)(rate(mite_http_response_time_seconds_bucket[10s])))) < 60",
     "legendFormat": "99.999%"
    },
    {
     "expr": "(histogram_quantile(0.9999, sum without(job)(rate(mite_http_response_time_seconds_bucket[10s])))) < 60",
     "legendFormat": "99.99%"
    },
    {
     "expr": "(histogram_quantile(0.999, sum without(job)(rate(mite_http_response_time_seconds_bucket[10s])))) < 60",
     "legendFormat": "99.9%"
    },
    {
     "expr": "(histogram_quantile(0.99, sum without(job)(rate(mite_http_response_time_seconds_bucket[10s])))) < 60\n",
     "legendFormat": "99%"
    },
    {
     "expr": "(histogram_quantile(0.95, sum without(job)(rate(mite_http_response_time_seconds_bucket[10s])))) < 60",
     "legendFormat": "95%"
    },
    {
     "expr": "(histogram_quantile(0.9, sum without(job)(rate(mite_http_response_time_seconds_bucket[10s])))) < 60",
     "legendFormat": "90%"
    },
    {
     "expr": "(histogram_quantile(0.75, sum without(job)(rate(mite_http_response_time_seconds_bucket[10s])))) < 60",
     "legendFormat": "75%"
    },
    {
     "expr": "(histogram_quantile(0.5, sum without(job)(rate(mite_http_response_time_seconds_bucket[10s])))) < 60",
     "legendFormat": "50%"
    },
    {
     "expr": "(histogram_quantile(0.25, sum without(job)(rate(mite_http_response_time_seconds_bucket[10s])))) < 60",
     "legendFormat": "25%"
    }
   ]
  },
  {
   "title": "HTTP Responses Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "TPS" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, job, journey, transaction, response_code, method)(rate(mite_http_response_total[10s]))",
     "legendFormat": "Total requests"
    },
    {
     "expr": "sum without(instance, job, journey, transaction)(rate(mite_http_response_total[10s]))",
     "legendFormat": " {{method}}  {{response_code}}"
    }
   ]
  },
  {
   "title": "Journeys Failed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(mite_transaction_total{had_error=\"True\", transaction!=\"__root__\"}[10s]) / on (transaction, journey, test) sum(rate(mite_transaction_total{ transaction!=\"__root__\"}[10s])) without (had_error) * 100",
     "legendFormat": "{{transaction}}"
    }
   ]
  },
  {
   "title": "Slowest Response Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(histogram_quantile(0.99, sum without(code, job, instance, method, journey, test)(rate(mite_http_response_time_seconds_bucket[10s]))) > 1) < 60",
     "legendFormat": "{{transaction}}"
    }
   ]
  },
  {
   "title": "Transactions/Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "TPS" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, job, journey, test)(rate(mite_transaction_total[10s]))",
     "legendFormat": "{{transaction}}"
    }
   ]
  },
  {
   "title": "Journey Starts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, job, transaction)(rate(mite_transaction_total[10s]))",
     "legendFormat": "{{journey}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, job)(rate(mite_journey_error_total[10s]))",
     "legendFormat": "{{journey}} - {{transaction}} - {{message}} {{location}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum without(instance, job, test, transaction)(rate(mite_journey_error_total[10s])) > 0"
    }
   ]
  },
  {
   "title": "Active Runners",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(mite_runner_count)", "legendFormat": "Active Runners" }
   ]
  },
  {
   "title": "Percentage Transactions Failed",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "rate(mite_transaction_total{had_error=\"True\",transaction!=\"__root__\"}[$time_range]) / on (transaction, journey, test) (sum(rate(mite_transaction_total{transaction!=\"__root__\"}[$time_range])) by (transaction, journey, test) > 0) * 100"
    }
   ]
  },
  {
   "title": "Actual vs required jobs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, job, scenario_id, test) (mite_required_count)",
     "legendFormat": "Required"
    },
    {
     "expr": "sum without(instance, job, scenario_id, test) (mite_actual_count)",
     "legendFormat": "Actual"
    }
   ]
  }
 ]
}